server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Zjy5a6a7925.
    url: jdbc:mysql://localhost:3306/zjy?serverTimezone=GMT%2b8

mybatis:
  mapper-locations: classpath:mapper/*.xml       #扫描xml文件


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #打印sql配置